export const TOOLS_DATA = [
  {
    "id": "compress",
    "toolId": "compress",
    "slug": "comprimir-imagen",
    "name": "Comprimir imagen",
    "title": "Comprimir imagen online gratis | Toolisto",
    "description": "Reduce el peso de una imagen manteniendo buena calidad directamente en tu navegador.",
    "summary": "Reduce el tamaño de archivo de una imagen sin perder calidad visible.",
    "category": "images",
    "icon": "↘"
  },
  {
    "id": "crop",
    "toolId": "crop",
    "slug": "redimensionar-imagen",
    "name": "Cambiar tamaño y recortar",
    "title": "Redimensionar y recortar imagen online | Toolisto",
    "description": "Recorta y redimensiona imágenes con precisión. Incluye presets para redes sociales y formatos estándar.",
    "summary": "Recorta y cambia el tamaño de una imagen con dimensiones exactas.",
    "category": "images",
    "icon": "⌗"
  },
  {
    "id": "convert",
    "toolId": "convert",
    "slug": "convertir-imagen",
    "name": "Convertir imagen",
    "title": "Convertir imagen a JPG PNG WebP online | Toolisto",
    "description": "Convierte imágenes entre JPEG, PNG y WebP. Soporta una o varias imágenes a la vez.",
    "summary": "Cambia el formato de una o varias imágenes entre JPEG, PNG y WebP.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "batchCompress",
    "toolId": "batchCompress",
    "slug": "comprimir-imagenes",
    "name": "Comprimir varias imágenes",
    "title": "Comprimir varias imágenes a la vez online | Toolisto",
    "description": "Reduce el peso de múltiples imágenes simultáneamente. Descarga todas en un ZIP.",
    "summary": "Reduce el peso de varias imágenes a la vez con una meta de tamaño en KB.",
    "category": "images",
    "icon": "⇊"
  },
  {
    "id": "stripMetadata",
    "toolId": "stripMetadata",
    "slug": "eliminar-metadatos-de-imagen",
    "name": "Eliminar metadatos",
    "title": "Eliminar metadatos de imagen online | Toolisto",
    "description": "Quita información de GPS, fecha, dispositivo y otros metadatos de tus imágenes.",
    "summary": "Elimina los metadatos visibles de una o varias imágenes.",
    "category": "images",
    "icon": "◈"
  },
  {
    "id": "socialCrop",
    "toolId": "socialCrop",
    "slug": "recortar-imagen-para-redes-sociales",
    "name": "Recortar para redes",
    "title": "Recortar imagen para redes sociales online | Toolisto",
    "description": "Adapta tu imagen a los formatos de TikTok, Instagram, YouTube y otras plataformas.",
    "summary": "Prepara tu imagen para publicar en redes sociales con el tamaño correcto.",
    "category": "images",
    "icon": "▣"
  },
  {
    "id": "removeObjects",
    "toolId": "removeObjects",
    "slug": "borrar-objetos-de-imagen",
    "name": "Borrar objetos y texto",
    "title": "Borrar objetos y texto de una imagen online | Toolisto",
    "description": "Elimina elementos no deseados de una imagen pintando sobre ellos con un pincel.",
    "summary": "Elimina objetos, texto o elementos de una imagen usando un pincel manual.",
    "category": "images",
    "icon": "◐"
  },
  {
    "id": "signature",
    "toolId": "signature",
    "slug": "limpiar-firma",
    "name": "Limpiar firma",
    "title": "Limpiar firma y quitar fondo online | Toolisto",
    "description": "Extrae una firma de un documento y descárgala como PNG transparente.",
    "summary": "Extrae una firma y exporta un PNG con fondo transparente.",
    "category": "signatures",
    "icon": "✦"
  },
  {
    "id": "mergePdf",
    "toolId": "mergePdf",
    "slug": "unir-pdf",
    "name": "Unir PDF",
    "title": "Unir PDF gratis online | Toolisto",
    "description": "Combina varios archivos PDF en un solo documento. Elige el orden que prefieras.",
    "summary": "Combina varios documentos PDF en un solo archivo.",
    "category": "pdf",
    "icon": "⊕"
  },
  {
    "id": "imagesPdf",
    "toolId": "imagesPdf",
    "slug": "imagenes-a-pdf",
    "name": "Imágenes a PDF",
    "title": "Convertir imágenes a PDF online | Toolisto",
    "description": "Crea un PDF a partir de una o varias imágenes. Respetando el orden visible.",
    "summary": "Convierte una o varias imágenes en un archivo PDF.",
    "category": "pdf",
    "icon": "▤"
  },
  {
    "id": "splitPdf",
    "toolId": "splitPdf",
    "slug": "dividir-pdf",
    "name": "Dividir PDF",
    "title": "Dividir PDF extraer páginas online | Toolisto",
    "description": "Extrae páginas específicas de un PDF por rangos o selección visual.",
    "summary": "Extrae páginas individuales o por rangos de un documento PDF.",
    "category": "pdf",
    "icon": "⊟"
  },
  {
    "id": "reorderPdf",
    "toolId": "reorderPdf",
    "slug": "organizar-pdf",
    "name": "Organizar PDF",
    "title": "Organizar y reordenar páginas PDF online | Toolisto",
    "description": "Reordena las páginas de un PDF arrastrándolas a la posición que desees.",
    "summary": "Reordena las páginas de un PDF arrastrándolas.",
    "category": "pdf",
    "icon": "⇶"
  },
  {
    "id": "pdfToImages",
    "toolId": "pdfToImages",
    "slug": "pdf-a-imagenes",
    "name": "PDF a imágenes",
    "title": "Convertir PDF a imágenes JPG PNG online | Toolisto",
    "description": "Convierte cada página de un PDF en una imagen descargable.",
    "summary": "Convierte las páginas de un PDF en imágenes JPEG, PNG o WebP.",
    "category": "pdf",
    "icon": "⬒"
  },
  {
    "id": "signPdf",
    "toolId": "signPdf",
    "slug": "firmar-pdf",
    "name": "Firmar PDF",
    "title": "Firmar PDF online gratis | Toolisto",
    "description": "Dibuja o escribe tu firma y colócala en un documento PDF directamente en tu navegador.",
    "summary": "Dibuja o escribe tu firma y colócala en un documento PDF.",
    "category": "signatures",
    "icon": "✎"
  },
  {
    "id": "docPhoto",
    "toolId": "docPhoto",
    "slug": "foto-para-documentos",
    "name": "Foto para documentos",
    "title": "Foto para documentos pasaporte visa DNI | Toolisto",
    "description": "Prepara fotos para pasaporte, visa, DNI y otros documentos oficiales.",
    "summary": "Genera fotos con las dimensiones correctas para pasaporte, visa, DNI y más.",
    "category": "images",
    "icon": "⊡"
  },
  {
    "id": "censor",
    "toolId": "censor",
    "slug": "censurar-imagen",
    "name": "Censurar información",
    "title": "Censurar información en imagen online | Toolisto",
    "description": "Oculta datos sensibles con pixelado, desenfoque o bloques de color.",
    "summary": "Oculta datos sensibles de una imagen con distintos métodos de censura.",
    "category": "images",
    "icon": "▓"
  },
  {
    "id": "fixFormat",
    "toolId": "fixFormat",
    "slug": "reparar-formato-de-imagen",
    "name": "Reparar formato",
    "title": "Reparar formato de imagen online | Toolisto",
    "description": "Detecta la extensión real de un archivo y corrige si tiene la extensión incorrecta.",
    "summary": "Detecta el formato real de un archivo y corrige la extensión si es necesario.",
    "category": "images",
    "icon": "⟳"
  },
  {
    "id": "rescueDoc",
    "toolId": "rescueDoc",
    "slug": "mejorar-documento-fotografiado",
    "name": "Rescatar documento",
    "title": "Mejorar foto de documento online | Toolisto",
    "description": "Mejora la iluminación, contraste y nitidez de documentos fotografiados.",
    "summary": "Mejora la legibilidad de fotos de documentos con ajustes automáticos y manuales.",
    "category": "images",
    "icon": "⊞"
  },
  {
    "id": "fileCompliance",
    "toolId": "fileCompliance",
    "slug": "cumplir-requisitos-de-archivo",
    "name": "Cumplir requisitos",
    "title": "Validar y ajustar archivo a requisitos online | Toolisto",
    "description": "Valida tu archivo contra requisitos específicos y ajusta automáticamente.",
    "summary": "Valida y ajusta un archivo a requisitos de peso, dimensiones y formato.",
    "category": "images",
    "icon": "☑"
  },
  {
    "id": "workflow",
    "toolId": "workflow",
    "slug": "flujo-de-imagenes",
    "name": "Flujo reutilizable",
    "title": "Crear flujo de procesamiento de imágenes | Toolisto",
    "description": "Encadena múltiples operaciones en una sola acción reutilizable.",
    "summary": "Crea y guarda flujos de procesamiento para encadenar múltiples operaciones.",
    "category": "images",
    "icon": "⛓"
  },
  {
    "id": "advancedConvert",
    "toolId": "advancedConvert",
    "slug": "conversor-avanzado-de-imagenes",
    "name": "Conversor avanzado",
    "title": "Conversor avanzado de imágenes online | Toolisto",
    "description": "Convierte, redimensiona, rota y añade marca de agua a tus imágenes.",
    "summary": "Convierte, redimensiona, rota, voltea y añade marca de agua a una o varias imágenes.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "jpg-to-png",
    "toolId": "convert",
    "slug": "jpg-a-png",
    "name": "JPG a PNG",
    "title": "Convertir JPG a PNG online gratis | Toolisto",
    "description": "Convierte imágenes JPG a PNG con soporte de transparencia. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes JPG al formato PNG.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "png-to-jpg",
    "toolId": "convert",
    "slug": "png-a-jpg",
    "name": "PNG a JPG",
    "title": "Convertir PNG a JPG online gratis | Toolisto",
    "description": "Convierte imágenes PNG a JPG con compresión eficiente. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes PNG al formato JPG.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "jpg-to-webp",
    "toolId": "convert",
    "slug": "jpg-a-webp",
    "name": "JPG a WebP",
    "title": "Convertir JPG a WebP online gratis | Toolisto",
    "description": "Convierte imágenes JPG a WebP para optimizar peso en web. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes JPG al formato WebP.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "webp-to-jpg",
    "toolId": "convert",
    "slug": "webp-a-jpg",
    "name": "WebP a JPG",
    "title": "Convertir WebP a JPG online gratis | Toolisto",
    "description": "Convierte imágenes WebP a JPG para máxima compatibilidad. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes WebP al formato JPG.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "png-to-webp",
    "toolId": "convert",
    "slug": "png-a-webp",
    "name": "PNG a WebP",
    "title": "Convertir PNG a WebP online gratis | Toolisto",
    "description": "Convierte PNG a WebP manteniendo transparencia y reduciendo peso. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes PNG al formato WebP.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "webp-to-png",
    "toolId": "convert",
    "slug": "webp-a-png",
    "name": "WebP a PNG",
    "title": "Convertir WebP a PNG online gratis | Toolisto",
    "description": "Convierte WebP a PNG sin pérdida de calidad. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes WebP al formato PNG.",
    "category": "images",
    "icon": "⇄"
  },
  {
    "id": "jpg-to-pdf",
    "toolId": "imagesPdf",
    "slug": "jpg-a-pdf",
    "name": "JPG a PDF",
    "title": "Convertir JPG a PDF online gratis | Toolisto",
    "description": "Convierte imágenes JPG a un documento PDF. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes JPG a un archivo PDF.",
    "category": "pdf",
    "icon": "▤"
  },
  {
    "id": "png-to-pdf",
    "toolId": "imagesPdf",
    "slug": "png-a-pdf",
    "name": "PNG a PDF",
    "title": "Convertir PNG a PDF online gratis | Toolisto",
    "description": "Convierte imágenes PNG a un documento PDF. Directamente en tu navegador.",
    "summary": "Convierte una o varias imágenes PNG a un archivo PDF.",
    "category": "pdf",
    "icon": "▤"
  },
  {
    "id": "pdf-to-jpg",
    "toolId": "pdfToImages",
    "slug": "pdf-a-jpg",
    "name": "PDF a JPG",
    "title": "Convertir PDF a JPG online gratis | Toolisto",
    "description": "Convierte cada página de un PDF en una imagen JPG. Directamente en tu navegador.",
    "summary": "Convierte las páginas de un PDF en imágenes JPG.",
    "category": "pdf",
    "icon": "⬒"
  },
  {
    "id": "pdf-to-png",
    "toolId": "pdfToImages",
    "slug": "pdf-a-png",
    "name": "PDF a PNG",
    "title": "Convertir PDF a PNG online gratis | Toolisto",
    "description": "Convierte cada página de un PDF en una imagen PNG de alta calidad. Directamente en tu navegador.",
    "summary": "Convierte las páginas de un PDF en imágenes PNG.",
    "category": "pdf",
    "icon": "⬒"
  },
  {
    "id": "wordToPdf",
    "toolId": "wordToPdf",
    "slug": "word-a-pdf",
    "name": "Word a PDF",
    "title": "Convertir Word a PDF online gratis | Toolisto",
    "description": "Convierte documentos DOC y DOCX a PDF directamente en tu navegador. Conserva textos, imágenes y tablas.",
    "summary": "Convierte documentos Word (DOC, DOCX) a formato PDF.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "wordToJpg",
    "toolId": "wordToJpg",
    "slug": "word-a-jpg",
    "name": "Word a JPG",
    "title": "Convertir Word a JPG online gratis | Toolisto",
    "description": "Convierte páginas de documentos Word a imágenes JPG. Cada página se renderiza como una imagen individual.",
    "summary": "Convierte las páginas de documentos Word (DOC, DOCX) a imágenes JPG.",
    "category": "documents",
    "icon": "🖼"
  },
  {
    "id": "wordToPng",
    "toolId": "wordToPng",
    "slug": "word-a-png",
    "name": "Word a PNG",
    "title": "Convertir Word a PNG online gratis | Toolisto",
    "description": "Convierte páginas de documentos Word a imágenes PNG de alta calidad sin pérdida. Ideal para impresión.",
    "summary": "Convierte las páginas de documentos Word (DOC, DOCX) a imágenes PNG sin pérdida.",
    "category": "documents",
    "icon": "🖼"
  },
  {
    "id": "wordToTxt",
    "toolId": "wordToTxt",
    "slug": "word-a-txt",
    "name": "Word a TXT",
    "title": "Convertir Word a TXT online gratis | Toolisto",
    "description": "Extrae solo el texto de documentos Word eliminando formato, imágenes y diseño. Rápido y directo.",
    "summary": "Extrae el texto plano de documentos Word (DOC, DOCX) sin formato.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "wordToHtml",
    "toolId": "wordToHtml",
    "slug": "word-a-html",
    "name": "Word a HTML",
    "title": "Convertir Word a HTML online gratis | Toolisto",
    "description": "Convierte documentos Word a HTML preservando formato, imágenes y estructura para web.",
    "summary": "Convierte documentos Word (DOC, DOCX) a código HTML con formato preservado.",
    "category": "documents",
    "icon": "🌐"
  },
  {
    "id": "wordToMarkdown",
    "toolId": "wordToMarkdown",
    "slug": "word-a-markdown",
    "name": "Word a Markdown",
    "title": "Convertir Word a Markdown online gratis | Toolisto",
    "description": "Convierte documentos Word a formato Markdown. Ideal para documentación y repositorios.",
    "summary": "Convierte documentos Word (DOC, DOCX) a formato Markdown.",
    "category": "documents",
    "icon": "📋"
  },
  {
    "id": "wordToEpub",
    "toolId": "wordToEpub",
    "slug": "word-a-epub",
    "name": "Word a EPUB",
    "title": "Convertir Word a EPUB online gratis | Toolisto",
    "description": "Convierte documentos Word a formato EPUB para lectores electrónicos. Preserva estructura y formato.",
    "summary": "Convierte documentos Word (DOC, DOCX) a formato EPUB para e-readers.",
    "category": "documents",
    "icon": "📚"
  },
  {
    "id": "wordToOdt",
    "toolId": "wordToOdt",
    "slug": "word-a-odt",
    "name": "Word a ODT",
    "title": "Convertir Word a ODT online gratis | Toolisto",
    "description": "Convierte documentos Word (DOC/DOCX) al formato ODT de OpenDocument. Compatible con LibreOffice.",
    "summary": "Convierte documentos Word (DOC, DOCX) al formato ODT de OpenDocument.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "odtToWord",
    "toolId": "odtToWord",
    "slug": "odt-a-word",
    "name": "ODT a Word",
    "title": "Convertir ODT a Word online gratis | Toolisto",
    "description": "Convierte documentos ODT de OpenDocument a formato DOCX de Microsoft Word.",
    "summary": "Convierte documentos ODT al formato DOCX de Microsoft Word.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "rtfToWord",
    "toolId": "rtfToWord",
    "slug": "rtf-a-word",
    "name": "RTF a Word",
    "title": "Convertir RTF a Word online gratis | Toolisto",
    "description": "Convierte archivos RTF a formato DOCX de Microsoft Word preservando texto, formato e imágenes.",
    "summary": "Convierte archivos RTF al formato DOCX de Microsoft Word.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "mergeWord",
    "toolId": "mergeWord",
    "slug": "unir-documentos-word",
    "name": "Unir documentos Word",
    "title": "Unir documentos Word online gratis | Toolisto",
    "description": "Combina varios archivos DOC/DOCX en un solo documento. Elige el orden de los archivos.",
    "summary": "Combina varios archivos Word en un solo documento DOCX.",
    "category": "documents",
    "icon": "📝"
  },
  {
    "id": "splitWord",
    "toolId": "splitWord",
    "slug": "dividir-documento-word",
    "name": "Dividir documento Word",
    "title": "Dividir documento Word online gratis | Toolisto",
    "description": "Divide un documento Word en varios archivos por páginas, secciones o rango de páginas.",
    "summary": "Divide un archivo Word en varios documentos por páginas o rangos.",
    "category": "documents",
    "icon": "✂"
  },
  {
    "id": "repairWord",
    "toolId": "repairWord",
    "slug": "reparar-word",
    "name": "Reparar documento Word",
    "title": "Reparar documento Word dañado online | Toolisto",
    "description": "Intenta recuperar y reparar documentos Word dañados o corruptos que no se pueden abrir.",
    "summary": "Repara documentos Word dañados o corruptos para recuperar su contenido.",
    "category": "documents",
    "icon": "🔧"
  },
  {
    "id": "compressWord",
    "toolId": "compressWord",
    "slug": "comprimir-word",
    "name": "Comprimir Word",
    "title": "Comprimir documento Word online | Toolisto",
    "description": "Reduce el tamaño de archivos Word optimizando imágenes embebidas y eliminando datos innecesarios.",
    "summary": "Reduce el peso de archivos Word optimizando imágenes y eliminando datos redundantes.",
    "category": "documents",
    "icon": "📦"
  },
  {
    "id": "stripMetadataWord",
    "toolId": "stripMetadataWord",
    "slug": "eliminar-metadatos-word",
    "name": "Eliminar metadatos de Word",
    "title": "Eliminar metadatos de documento Word online | Toolisto",
    "description": "Elimina autor, fecha, historial de revisiones y otros metadatos de documentos Word.",
    "summary": "Elimina los metadatos ocultos de documentos Word como autor, fecha e historial.",
    "category": "documents",
    "icon": "🔒"
  },
  {
    "id": "formatDocument",
    "toolId": "formatDocument",
    "slug": "uniformar-formato-documento",
    "name": "Uniformar formato",
    "title": "Uniformar formato de documento online | Toolisto",
    "description": "Aplica un formato consistente a todo el documento: fuente, tamaño, interlineado y márgenes.",
    "summary": "Normaliza el formato de un documento Word con fuente, tamaño y espaciado consistentes.",
    "category": "documents",
    "icon": "🎨"
  },
  {
    "id": "tocWord",
    "toolId": "tocWord",
    "slug": "crear-tabla-de-contenido",
    "name": "Crear tabla de contenido",
    "title": "Crear tabla de contenido en Word online | Toolisto",
    "description": "Genera una tabla de contenido automática en un documento Word a partir de sus encabezados.",
    "summary": "Genera una tabla de contenido automática basada en los encabezados de un documento Word.",
    "category": "documents",
    "icon": "📑"
  },
  {
    "id": "extractWord",
    "toolId": "extractWord",
    "slug": "extraer-contenido-word",
    "name": "Extraer contenido de Word",
    "title": "Extraer contenido de documento Word online | Toolisto",
    "description": "Extrae texto, tablas, imágenes y listas de documentos Word a TXT, CSV, JSON o ZIP.",
    "summary": "Extrae diferentes tipos de contenido de documentos Word a varios formatos.",
    "category": "documents",
    "icon": "📤"
  },
  {
    "id": "findReplaceWord",
    "toolId": "findReplaceWord",
    "slug": "buscar-reemplazar-documentos",
    "name": "Buscar y reemplazar",
    "title": "Buscar y reemplazar en documentos Word online | Toolisto",
    "description": "Busca y reemplaza texto en uno o varios documentos Word de forma masiva.",
    "summary": "Realiza búsquedas y reemplazos de texto en documentos Word de forma masiva.",
    "category": "documents",
    "icon": "🔍"
  },
  {
    "id": "tablesWordToExcel",
    "toolId": "tablesWordToExcel",
    "slug": "tablas-word-a-excel",
    "name": "Tablas Word a Excel",
    "title": "Convertir tablas de Word a Excel online | Toolisto",
    "description": "Extrae todas las tablas de un documento Word y las convierte a hojas de cálculo Excel.",
    "summary": "Extrae tablas de documentos Word y las exporta a formato Excel (XLSX).",
    "category": "documents",
    "icon": "📊"
  },
  {
    "id": "removeBlankPagesWord",
    "toolId": "removeBlankPagesWord",
    "slug": "eliminar-paginas-en-blanco-word",
    "name": "Eliminar páginas en blanco",
    "title": "Eliminar páginas en blanco de Word online | Toolisto",
    "description": "Detecta y elimina páginas en blanco innecesarias de documentos Word automáticamente.",
    "summary": "Elimina automáticamente las páginas en blanco vacías de documentos Word.",
    "category": "documents",
    "icon": "📄"
  },
  {
    "id": "txtToPdf",
    "toolId": "txtToPdf",
    "slug": "txt-a-pdf",
    "name": "TXT a PDF",
    "title": "Convertir TXT a PDF online gratis | Toolisto",
    "description": "Convierte archivos de texto plano TXT a documentos PDF con formato profesional.",
    "summary": "Convierte archivos de texto plano TXT al formato PDF.",
    "category": "text",
    "icon": "📄"
  },
  {
    "id": "txtToEpub",
    "toolId": "txtToEpub",
    "slug": "txt-a-epub",
    "name": "TXT a EPUB",
    "title": "Convertir TXT a EPUB online gratis | Toolisto",
    "description": "Convierte archivos TXT a formato EPUB para leer en cualquier dispositivo o lector electrónico.",
    "summary": "Convierte archivos de texto plano TXT al formato EPUB para e-readers.",
    "category": "text",
    "icon": "📚"
  },
  {
    "id": "mergeTxt",
    "toolId": "mergeTxt",
    "slug": "unir-archivos-txt",
    "name": "Unir archivos TXT",
    "title": "Unir archivos TXT online gratis | Toolisto",
    "description": "Combina varios archivos de texto plano TXT en un solo archivo manteniendo el orden que elijas.",
    "summary": "Combina varios archivos TXT en un solo archivo de texto.",
    "category": "text",
    "icon": "📎"
  },
  {
    "id": "splitTxt",
    "toolId": "splitTxt",
    "slug": "dividir-archivo-txt",
    "name": "Dividir archivo TXT",
    "title": "Dividir archivo TXT online gratis | Toolisto",
    "description": "Divide un archivo TXT por número de líneas, por caracteres o por separadores personalizados.",
    "summary": "Divide un archivo TXT en varios fragmentos por líneas o por tamaño.",
    "category": "text",
    "icon": "✂"
  },
  {
    "id": "sortLines",
    "toolId": "sortLines",
    "slug": "ordenar-lineas-texto",
    "name": "Ordenar líneas de texto",
    "title": "Ordenar líneas de texto online gratis | Toolisto",
    "description": "Ordena las líneas de un archivo TXT alfabéticamente, por longitud o en orden inverso.",
    "summary": "Ordena las líneas de un archivo TXT de forma alfanumérica o personalizada.",
    "category": "text",
    "icon": "🔤"
  },
  {
    "id": "removeDuplicates",
    "toolId": "removeDuplicates",
    "slug": "eliminar-filas-duplicadas",
    "name": "Eliminar filas duplicadas",
    "title": "Eliminar filas duplicadas de texto online | Toolisto",
    "description": "Elimina líneas duplicadas de archivos TXT, conservando solo la primera aparición de cada una.",
    "summary": "Elimina las líneas duplicadas de un archivo TXT manteniendo solo ocurrencias únicas.",
    "category": "text",
    "icon": "🗑"
  },
  {
    "id": "listToTable",
    "toolId": "listToTable",
    "slug": "convertir-listas-en-tablas",
    "name": "Convertir listas en tablas",
    "title": "Convertir listas a tablas online | Toolisto",
    "description": "Convierte listas de texto, CSV o valores separados por comas en tablas HTML, CSV, Markdown o Excel.",
    "summary": "Transforma listas de texto en tablas estructuradas con múltiples formatos de salida.",
    "category": "text",
    "icon": "📊"
  },
  {
    "id": "epubToTxt",
    "toolId": "epubToTxt",
    "slug": "epub-a-txt",
    "name": "EPUB a TXT",
    "title": "Convertir EPUB a TXT online gratis | Toolisto",
    "description": "Extrae el texto completo de archivos EPUB eliminando formato, imágenes y diseño.",
    "summary": "Extrae el texto plano de archivos EPUB sin formato ni diseño.",
    "category": "ebooks",
    "icon": "📄"
  },
  {
    "id": "epubToHtml",
    "toolId": "epubToHtml",
    "slug": "epub-a-html",
    "name": "EPUB a HTML",
    "title": "Convertir EPUB a HTML online gratis | Toolisto",
    "description": "Convierte archivos EPUB a HTML preservando estructura, formato, imágenes y capítulos.",
    "summary": "Convierte archivos EPUB a páginas HTML con formato preservado.",
    "category": "ebooks",
    "icon": "🌐"
  },
  {
    "id": "epubToMarkdown",
    "toolId": "epubToMarkdown",
    "slug": "epub-a-markdown",
    "name": "EPUB a Markdown",
    "title": "Convertir EPUB a Markdown online gratis | Toolisto",
    "description": "Convierte archivos EPUB a formato Markdown preservando capítulos, formato y estructura.",
    "summary": "Convierte archivos EPUB a formato Markdown con estructura de capítulos.",
    "category": "ebooks",
    "icon": "📋"
  },
  {
    "id": "mergeEpub",
    "toolId": "mergeEpub",
    "slug": "unir-epub",
    "name": "Unir libros EPUB",
    "title": "Unir libros EPUB online gratis | Toolisto",
    "description": "Combina varios archivos EPUB en un solo libro electrónico manteniendo capítulos y formato.",
    "summary": "Combina varios archivos EPUB en un solo libro electrónico.",
    "category": "ebooks",
    "icon": "📚"
  },
  {
    "id": "splitEpub",
    "toolId": "splitEpub",
    "slug": "dividir-epub-por-capitulos",
    "name": "Dividir EPUB por capítulos",
    "title": "Dividir EPUB por capítulos online | Toolisto",
    "description": "Divide un archivo EPUB en varios archivos separados por capítulo o por rango de páginas.",
    "summary": "Divide un archivo EPUB en varios archivos EPUB por capítulo o por rango.",
    "category": "ebooks",
    "icon": "✂"
  },
  {
    "id": "editMetadataEpub",
    "toolId": "editMetadataEpub",
    "slug": "editar-metadatos-epub",
    "name": "Editar metadatos EPUB",
    "title": "Editar metadatos de EPUB online | Toolisto",
    "description": "Modifica título, autor, idioma, descripción y otros metadatos de archivos EPUB.",
    "summary": "Modifica los metadatos de un archivo EPUB: título, autor, idioma y más.",
    "category": "ebooks",
    "icon": "🏷"
  },
  {
    "id": "coverEpub",
    "toolId": "coverEpub",
    "slug": "extraer-portada-epub",
    "name": "Extraer portada EPUB",
    "title": "Extraer portada de EPUB online | Toolisto",
    "description": "Extrae la imagen de portada de un archivo EPUB y la descarga como imagen JPG, PNG o WebP.",
    "summary": "Extrae la imagen de portada de un archivo EPUB en formato imagen.",
    "category": "ebooks",
    "icon": "🖼"
  },
  {
    "id": "imagesEpub",
    "toolId": "imagesEpub",
    "slug": "extraer-imagenes-epub",
    "name": "Extraer imágenes EPUB",
    "title": "Extraer imágenes de EPUB online | Toolisto",
    "description": "Extrae todas las imágenes de un archivo EPUB (ilustraciones, portadas, fotografías) en JPG, PNG o ZIP.",
    "summary": "Extrae todas las imágenes contenidas en un archivo EPUB.",
    "category": "ebooks",
    "icon": "🖼"
  },
  {
    "id": "validateEpub",
    "toolId": "validateEpub",
    "slug": "validar-epub",
    "name": "Validar EPUB",
    "title": "Validar archivo EPUB online | Toolisto",
    "description": "Valida un archivo EPUB contra el estándar EPUB 3 y muestra errores, advertencias e información.",
    "summary": "Valida la estructura y conformidad de un archivo EPUB con el estándar.",
    "category": "ebooks",
    "icon": "✅"
  },
  {
    "id": "repairEpub",
    "toolId": "repairEpub",
    "slug": "reparar-epub",
    "name": "Reparar EPUB",
    "title": "Reparar archivo EPUB dañado online | Toolisto",
    "description": "Repara archivos EPUB dañados, corrige estructura interna y restaura enlaces rotos.",
    "summary": "Repara la estructura y contenido de archivos EPUB dañados o corruptos.",
    "category": "ebooks",
    "icon": "🔧"
  },
  {
    "id": "csvToExcel",
    "toolId": "csvToExcel",
    "slug": "csv-a-excel",
    "name": "CSV a Excel",
    "title": "Convertir CSV a Excel online gratis | Toolisto",
    "description": "Convierte archivos CSV a formato Excel (XLSX) detectando automáticamente el separador y la codificación.",
    "summary": "Convierte archivos CSV a formato Excel (XLSX) de forma rápida y automática.",
    "category": "spreadsheets",
    "icon": "📊"
  },
  {
    "id": "excelToCsv",
    "toolId": "excelToCsv",
    "slug": "excel-a-csv",
    "name": "Excel a CSV",
    "title": "Exportar Excel a CSV online gratis | Toolisto",
    "description": "Exporta hojas de cálculo Excel a CSV con separador y codificación configurables.",
    "summary": "Exporta archivos Excel a formato CSV con configuración de separador y codificación.",
    "category": "spreadsheets",
    "icon": "📋"
  },
  {
    "id": "excelToJson",
    "toolId": "excelToJson",
    "slug": "excel-a-json",
    "name": "Excel a JSON",
    "title": "Convertir Excel a JSON online gratis | Toolisto",
    "description": "Convierte filas de Excel en objetos JSON con detección automática de tipos de datos.",
    "summary": "Convierte archivos Excel a JSON con detección automática de tipos de datos.",
    "category": "spreadsheets",
    "icon": "{ }"
  },
  {
    "id": "jsonToExcel",
    "toolId": "jsonToExcel",
    "slug": "json-a-excel",
    "name": "JSON a Excel",
    "title": "Convertir JSON a Excel online gratis | Toolisto",
    "description": "Convierte datos JSON en hojas de cálculo Excel editables.",
    "summary": "Convierte archivos JSON en hojas de cálculo Excel (.xlsx) editables.",
    "category": "spreadsheets",
    "icon": "📊"
  },
  {
    "id": "csvToJson",
    "toolId": "csvToJson",
    "slug": "csv-a-json",
    "name": "CSV a JSON",
    "title": "Convertir CSV a JSON online gratis | Toolisto",
    "description": "Convierte archivos CSV en JSON con detección automática de separador.",
    "summary": "Convierte archivos CSV a formato JSON con detección automática de separador.",
    "category": "spreadsheets",
    "icon": "{ }"
  },
  {
    "id": "jsonToCsv",
    "toolId": "jsonToCsv",
    "slug": "json-a-csv",
    "name": "JSON a CSV",
    "title": "Convertir JSON a CSV online gratis | Toolisto",
    "description": "Convierte archivos JSON en CSV con separador configurable.",
    "summary": "Convierte archivos JSON a formato CSV con separador configurable.",
    "category": "spreadsheets",
    "icon": "📋"
  },
  {
    "id": "xmlToJson",
    "toolId": "xmlToJson",
    "slug": "xml-a-json",
    "name": "XML a JSON",
    "title": "Convertir XML a JSON online gratis | Toolisto",
    "description": "Convierte archivos XML a JSON conservando jerarquía y atributos.",
    "summary": "Convierte archivos XML a formato JSON conservando la jerarquía y atributos.",
    "category": "spreadsheets",
    "icon": "{ }"
  },
  {
    "id": "jsonToXml",
    "toolId": "jsonToXml",
    "slug": "json-a-xml",
    "name": "JSON a XML",
    "title": "Convertir JSON a XML online gratis | Toolisto",
    "description": "Convierte datos JSON en XML válido con estructura configurable.",
    "summary": "Convierte archivos JSON a formato XML válido con estructura configurable.",
    "category": "spreadsheets",
    "icon": "📄"
  },
  {
    "id": "mergeExcel",
    "toolId": "mergeExcel",
    "slug": "unir-excel",
    "name": "Unir archivos Excel",
    "title": "Unir archivos Excel online gratis | Toolisto",
    "description": "Combina múltiples archivos Excel en un solo libro conservando todas las hojas.",
    "summary": "Combina múltiples archivos Excel en un solo libro con todas sus hojas.",
    "category": "spreadsheets",
    "icon": "🔗"
  },
  {
    "id": "splitExcel",
    "toolId": "splitExcel",
    "slug": "dividir-excel",
    "name": "Dividir archivo Excel",
    "title": "Dividir archivo Excel online gratis | Toolisto",
    "description": "Divide un archivo Excel por hojas, filas o rangos en múltiples archivos.",
    "summary": "Divide un archivo Excel en múltiples archivos por hojas, filas o rangos.",
    "category": "spreadsheets",
    "icon": "✂"
  },
  {
    "id": "compareExcel",
    "toolId": "compareExcel",
    "slug": "comparar-excel",
    "name": "Comparar archivos Excel",
    "title": "Comparar archivos Excel online gratis | Toolisto",
    "description": "Detecta diferencias entre dos archivos Excel celda por celda.",
    "summary": "Detecta diferencias celda por celda entre dos archivos Excel.",
    "category": "spreadsheets",
    "icon": "🔍"
  },
  {
    "id": "xlsToXlsx",
    "toolId": "xlsToXlsx",
    "slug": "xls-a-xlsx",
    "name": "XLS a XLSX",
    "title": "Convertir XLS a XLSX online gratis | Toolisto",
    "description": "Convierte archivos Excel antiguos (XLS) al formato moderno y compatible (XLSX).",
    "summary": "Convierte archivos Excel antiguos (XLS) al formato moderno (XLSX).",
    "category": "spreadsheets",
    "icon": "🔄"
  },
  {
    "id": "xlsxToOds",
    "toolId": "xlsxToOds",
    "slug": "xlsx-a-ods",
    "name": "XLSX a ODS",
    "title": "Convertir XLSX a ODS online gratis | Toolisto",
    "description": "Convierte archivos Excel al formato OpenDocument Spreadsheet compatible con LibreOffice.",
    "summary": "Convierte archivos Excel al formato OpenDocument Spreadsheet (ODS).",
    "category": "spreadsheets",
    "icon": "📄"
  },
  {
    "id": "odsToXlsx",
    "toolId": "odsToXlsx",
    "slug": "ods-a-xlsx",
    "name": "ODS a XLSX",
    "title": "Convertir ODS a XLSX online gratis | Toolisto",
    "description": "Convierte archivos LibreOffice Calc al formato Excel (XLSX) compatible universalmente.",
    "summary": "Convierte archivos ODS de LibreOffice al formato Excel (XLSX).",
    "category": "spreadsheets",
    "icon": "📊"
  },
  {
    "id": "rotatePdf",
    "toolId": "rotatePdf",
    "slug": "girar-pdf",
    "name": "Girar páginas PDF",
    "title": "Girar páginas PDF online gratis | Toolisto",
    "description": "Gira todas las páginas de un PDF 90°, 180° o 270° directamente en tu navegador.",
    "summary": "Cambia la orientación de las páginas de un documento PDF con un solo clic.",
    "category": "pdf",
    "icon": "↻"
  },
  {
    "id": "deletePagesPdf",
    "toolId": "deletePagesPdf",
    "slug": "eliminar-paginas-pdf",
    "name": "Eliminar páginas PDF",
    "title": "Eliminar páginas PDF online gratis | Toolisto",
    "description": "Elimina páginas específicas de un documento PDF por rango directamente en tu navegador.",
    "summary": "Selecciona y elimina las páginas que no necesitas de un documento PDF.",
    "category": "pdf",
    "icon": "✕"
  },
  {
    "id": "reversePagesPdf",
    "toolId": "reversePagesPdf",
    "slug": "invertir-orden-pdf",
    "name": "Invertir orden de páginas PDF",
    "title": "Invertir orden de páginas PDF online gratis | Toolisto",
    "description": "Invierte el orden de todas las páginas de un documento PDF en tu navegador.",
    "summary": "Pon las páginas de un PDF en orden inverso con un solo clic.",
    "category": "pdf",
    "icon": "⇅"
  },
  {
    "id": "duplicatePagesPdf",
    "toolId": "duplicatePagesPdf",
    "slug": "duplicar-paginas-pdf",
    "name": "Duplicar páginas PDF",
    "title": "Duplicar páginas PDF online gratis | Toolisto",
    "description": "Duplica todas o páginas específicas de un documento PDF en tu navegador.",
    "summary": "Repite páginas seleccionadas o todo el documento tantas veces como necesites.",
    "category": "pdf",
    "icon": "⧉"
  },
  {
    "id": "insertBlankPagesPdf",
    "toolId": "insertBlankPagesPdf",
    "slug": "insertar-paginas-en-blanco-pdf",
    "name": "Insertar páginas en blanco PDF",
    "title": "Insertar páginas en blanco en PDF online gratis | Toolisto",
    "description": "Inserta páginas vacías en posiciones específicas de un documento PDF en tu navegador.",
    "summary": "Añade hojas vacías donde las necesites de un documento PDF.",
    "category": "pdf",
    "icon": "＋"
  },
  {
    "id": "editMetadataPdf",
    "toolId": "editMetadataPdf",
    "slug": "editar-metadatos-pdf",
    "name": "Editar metadatos PDF",
    "title": "Editar metadatos PDF online gratis | Toolisto",
    "description": "Modifica el título, autor, asunto y palabras clave de un documento PDF en tu navegador.",
    "summary": "Actualiza la información del documento como título, autor y palabras clave.",
    "category": "pdf",
    "icon": "🏷"
  },
  {
    "id": "compressPdf",
    "toolId": "compressPdf",
    "slug": "comprimir-pdf",
    "name": "Comprimir PDF",
    "title": "Comprimir PDF online gratis | Toolisto",
    "description": "Elimina metadatos innecesarios y optimiza el tamaño del PDF sin cambiar el contenido.",
    "summary": "Reduce el tamaño de un PDF eliminando metadatos innecesarios y optimizando la estructura interna.",
    "category": "pdf",
    "icon": "📦"
  },
  {
    "id": "interleavePdf",
    "toolId": "interleavePdf",
    "slug": "intercalar-pdf",
    "name": "Intercalar páginas PDF",
    "title": "Intercalar páginas PDF online gratis | Toolisto",
    "description": "Alterna las páginas de dos documentos PDF en un solo archivo.",
    "summary": "Combina dos PDFs alternando sus páginas en un solo documento.",
    "category": "pdf",
    "icon": "🔗"
  },
  {
    "id": "cropPdf",
    "toolId": "cropPdf",
    "slug": "recortar-pdf",
    "name": "Recortar márgenes PDF",
    "title": "Recortar márgenes PDF online gratis | Toolisto",
    "description": "Elimina márgenes innecesarios de todas las páginas del PDF.",
    "summary": "Recorta los márgenes de todas las páginas de un PDF para reducir su tamaño.",
    "category": "pdf",
    "icon": "✂"
  },
  {
    "id": "resizePdfPages",
    "toolId": "resizePdfPages",
    "slug": "cambiar-tamano-paginas-pdf",
    "name": "Redimensionar páginas PDF",
    "title": "Redimensionar páginas PDF online gratis | Toolisto",
    "description": "Cambia el tamaño de las páginas a formato estándar como A4, Carta o Legal.",
    "summary": "Cambia el tamaño de las páginas de un PDF a formatos estándar como A4, Carta o Legal.",
    "category": "pdf",
    "icon": "↔"
  },
  {
    "id": "nUpPdf",
    "toolId": "nUpPdf",
    "slug": "varias-paginas-por-hoja-pdf",
    "name": "Varias páginas por hoja",
    "title": "Varias páginas por hoja PDF online gratis | Toolisto",
    "description": "Coloca 2 o 4 páginas en una sola hoja para ahorrar espacio al imprimir.",
    "summary": "Coloca 2 o 4 páginas de un PDF en una sola hoja para ahorrar espacio.",
    "category": "pdf",
    "icon": "⊞"
  },
  {
    "id": "splitDoublePdf",
    "toolId": "splitDoublePdf",
    "slug": "dividir-paginas-dobles-pdf",
    "name": "Dividir páginas dobles PDF",
    "title": "Dividir páginas dobles — Separar PDF escaneado a dos columnas",
    "description": "Divide páginas dobles de un PDF escaneado en páginas individuales. Corta vertical o horizontalmente.",
    "summary": "Separa automáticamente páginas dobles escaneadas en páginas individuales. Ideal para documentos escaneados con dos páginas por hoja.",
    "category": "pdf",
    "icon": "⫿"
  },
  {
    "id": "bookletPdf",
    "toolId": "bookletPdf",
    "slug": "crear-cuadernillo-pdf",
    "name": "Crear cuadernillo PDF",
    "title": "Crear cuadernillo PDF — Reordenar para impresión doble cara",
    "description": "Reordena las páginas de un PDF para imprimirlo como cuadernillo doble cara y plegarlo como un libro.",
    "summary": "Reordena las páginas de un PDF para poder imprimirlo como cuadernillo doble cara y plegarlo como un libro.",
    "category": "pdf",
    "icon": "⊞"
  },
  {
    "id": "watermarkPdf",
    "toolId": "watermarkPdf",
    "slug": "agregar-marca-de-agua-pdf",
    "name": "Agregar marca de agua a PDF",
    "title": "Agregar marca de agua a PDF — Texto BORRADOR o CONFIDENCIAL",
    "description": "Agrega una marca de agua de texto personalizado a todas las páginas de un PDF. Ideal para BORRADOR o CONFIDENCIAL.",
    "summary": "Añade un texto de marca de agua personalizado a todas las páginas de un PDF. Ideal para marcar documentos como BORRADOR o CONFIDENCIAL.",
    "category": "pdf",
    "icon": "⊡"
  },
  {
    "id": "addPageNumbersPdf",
    "toolId": "addPageNumbersPdf",
    "slug": "numerar-paginas-pdf",
    "name": "Numerar páginas PDF",
    "title": "Numerar páginas PDF — Agregar números de página",
    "description": "Agrega números de página en la posición y formato que elijas a todas las páginas de un PDF.",
    "summary": "Agrega números de página en la posición y formato que elijas. Soporta números, paréntesis, guiones y números romanos.",
    "category": "pdf",
    "icon": "№"
  },
  {
    "id": "addHeaderFooterPdf",
    "toolId": "addHeaderFooterPdf",
    "slug": "encabezado-pie-pdf",
    "name": "Encabezado y pie de página PDF",
    "title": "Encabezado y pie de página PDF — Agregar texto superior e inferior",
    "description": "Añade texto de encabezado y pie de página centrado en todas las páginas de un PDF.",
    "summary": "Añade texto de encabezado (arriba) y pie de página (abajo) centrado en todas las páginas del documento.",
    "category": "pdf",
    "icon": "≡"
  },
  {
    "id": "unzipFile",
    "toolId": "unzipFile",
    "slug": "extraer-zip",
    "name": "Extraer ZIP",
    "title": "Extraer archivo ZIP online gratis | Toolisto",
    "description": "Extrae el contenido de archivos ZIP directamente en tu navegador mostrando nombres, carpetas y tamaños antes de descargar.",
    "summary": "Extrae archivos ZIP y descarga su contenido de forma segura.",
    "category": "files",
    "icon": "📦"
  },
  {
    "id": "createZipAdvanced",
    "toolId": "createZipAdvanced",
    "slug": "crear-zip-avanzado",
    "name": "Crear ZIP avanzado",
    "title": "Crear archivo ZIP avanzado online | Toolisto",
    "description": "Crea archivos ZIP con múltiples archivos, carpetas virtuales, niveles de compresión y nombres personalizados.",
    "summary": "Crea ZIPs personalizados con múltiples archivos y opciones de compresión.",
    "category": "files",
    "icon": "🗜"
  },
  {
    "id": "zipRepair",
    "toolId": "zipRepair",
    "slug": "reparar-zip",
    "name": "Reparar ZIP",
    "title": "Reparar archivo ZIP dañado online | Toolisto",
    "description": "Intenta recuperar archivos de ZIPs dañados mostrando un informe detallado de entradas recuperadas y omitidas.",
    "summary": "Intenta recuperar contenido de archivos ZIP dañados o corruptos.",
    "category": "files",
    "icon": "🔧"
  },
  {
    "id": "fileSplit",
    "toolId": "fileSplit",
    "slug": "dividir-archivo",
    "name": "Dividir archivo grande",
    "title": "Dividir archivo grande online gratis | Toolisto",
    "description": "Divide archivos grandes en partes más pequeñas con tamaños predefinidos o personalizados e incluye un manifiesto.",
    "summary": "Divide un archivo grande en partes más pequeñas con nombres consistentes.",
    "category": "files",
    "icon": "✂"
  },
  {
    "id": "fileJoin",
    "toolId": "fileJoin",
    "slug": "unir-archivos-divididos",
    "name": "Unir archivos divididos",
    "title": "Unir archivos divididos online gratis | Toolisto",
    "description": "Reconstruye un archivo original a partir de sus partes, verificando hashes y detectando partes faltantes.",
    "summary": "Reconstruye un archivo original a partir de partes divididas.",
    "category": "files",
    "icon": "🔗"
  },
  {
    "id": "checksumFile",
    "toolId": "checksumFile",
    "slug": "calcular-hash",
    "name": "Calcular hash o checksum",
    "title": "Calcular hash SHA-256 online gratis | Toolisto",
    "description": "Calcula hash SHA-256, SHA-384, SHA-512 o SHA-1 de archivos directamente en tu navegador con Web Crypto API.",
    "summary": "Calcula hashes criptográficos de archivos de forma local y segura.",
    "category": "files",
    "icon": "🔢"
  },
  {
    "id": "fileInspector",
    "toolId": "fileInspector",
    "slug": "inspeccionar-archivo",
    "name": "Inspeccionar archivo",
    "title": "Inspeccionar archivo online gratis | Toolisto",
    "description": "Analiza un archivo local mostrando tipo MIME, firma detectada, tamaño, hash y metadatos sin ejecutarlo.",
    "summary": "Analiza las características técnicas de un archivo sin ejecutarlo.",
    "category": "files",
    "icon": "🔍"
  },
  {
    "id": "pdfEncryptAdvanced",
    "toolId": "pdfEncryptAdvanced",
    "slug": "encriptar-pdf-avanzado",
    "name": "Cifrado avanzado de PDF",
    "title": "Cifrar PDF con contraseña online | Toolisto",
    "description": "Protege un PDF con contraseña de apertura usando cifrado compatible con lectores PDF comunes.",
    "summary": "Protege tu PDF con contraseña de apertura usando cifrado real.",
    "category": "pdf",
    "icon": "🔒"
  },
  {
    "id": "qrGenerate",
    "toolId": "qrGenerate",
    "slug": "generar-qr",
    "name": "Generar código QR",
    "title": "Generar código QR online gratis | Toolisto",
    "description": "Genera códigos QR para texto, URL, correo, teléfono y más con opciones de color, tamaño y formato.",
    "summary": "Crea códigos QR personalizados con diferentes opciones de estilo.",
    "category": "qrcodes",
    "icon": "📱"
  },
  {
    "id": "qrWifi",
    "toolId": "qrWifi",
    "slug": "generar-qr-wifi",
    "name": "Generar QR de Wi-Fi",
    "title": "Generar QR de Wi-Fi online gratis | Toolisto",
    "description": "Genera un código QR con los datos de tu red Wi-Fi para compartir la contraseña de forma rápida.",
    "summary": "Comparte tu contraseña de Wi-Fi con un código QR.",
    "category": "qrcodes",
    "icon": "📶"
  },
  {
    "id": "qrVcard",
    "toolId": "qrVcard",
    "slug": "generar-qr-contacto",
    "name": "Generar QR de contacto vCard",
    "title": "Generar QR de contacto vCard online | Toolisto",
    "description": "Genera un código QR con tu información de contacto en formato vCard para compartir fácilmente.",
    "summary": "Crea un QR con tu información de contacto para compartir al instante.",
    "category": "qrcodes",
    "icon": "👤"
  },
  {
    "id": "barcodeGenerate",
    "toolId": "barcodeGenerate",
    "slug": "generar-codigo-barras",
    "name": "Generar código de barras",
    "title": "Generar código de barras online gratis | Toolisto",
    "description": "Genera códigos de barras en formato Code 128, Code 39, EAN-13, UPC-A e ITF con opciones personalizables.",
    "summary": "Crea códigos de barras en múltiples formatos con validación automática.",
    "category": "qrcodes",
    "icon": "条"
  },
  {
    "id": "qrReadFromImage",
    "toolId": "qrReadFromImage",
    "slug": "leer-qr-imagen",
    "name": "Leer QR desde imagen",
    "title": "Leer código QR desde imagen online | Toolisto",
    "description": "Decodifica códigos QR desde imágenes cargadas o capturadas con la cámara en móviles.",
    "summary": "Decodifica códigos QR desde una imagen o la cámara de tu dispositivo.",
    "category": "qrcodes",
    "icon": "📷"
  },
  {
    "id": "barcodeReadFromImage",
    "toolId": "barcodeReadFromImage",
    "slug": "leer-codigo-barras-imagen",
    "name": "Leer código de barras desde imagen",
    "title": "Leer código de barras desde imagen online | Toolisto",
    "description": "Decodifica códigos de barras 1D desde imágenes cargadas o capturadas con la cámara.",
    "summary": "Decodifica códigos de barras desde una imagen o la cámara.",
    "category": "qrcodes",
    "icon": "📸"
  },
  {
    "id": "qrBatchFromCsv",
    "toolId": "qrBatchFromCsv",
    "slug": "generar-qr-por-lote",
    "name": "Generar QR por lote desde CSV",
    "title": "Generar QR por lote desde CSV online | Toolisto",
    "description": "Genera múltiples códigos QR desde un archivo CSV con vista previa y descarga en ZIP.",
    "summary": "Genera un código QR por cada fila de un archivo CSV.",
    "category": "qrcodes",
    "icon": "📋"
  },
  {
    "id": "colorPicker",
    "toolId": "colorPicker",
    "slug": "selector-color",
    "name": "Selector de color desde imagen",
    "title": "Selector de color desde imagen online | Toolisto",
    "description": "Captura el color exacto de cualquier punto de una imagen con valores HEX, RGB y HSL.",
    "summary": "Obtén el color exacto de cualquier píxel de una imagen.",
    "category": "images",
    "icon": "🎨"
  },
  {
    "id": "imageCompare",
    "toolId": "imageCompare",
    "slug": "comparar-imagenes",
    "name": "Comparar dos imágenes",
    "title": "Comparar dos imágenes online gratis | Toolisto",
    "description": "Compara dos imágenes lado a lado con deslizador, alternancia, superposición y diferencia visual.",
    "summary": "Compara dos imágenes usando diferentes métodos de visualización.",
    "category": "images",
    "icon": "⚖"
  },
  {
    "id": "pdfPageCounter",
    "toolId": "pdfPageCounter",
    "slug": "contar-paginas-pdf",
    "name": "Contar páginas de PDF",
    "title": "Contar páginas de PDF online gratis | Toolisto",
    "description": "Cuenta las páginas de uno o varios PDFs, detecta archivos dañados e exporta un informe.",
    "summary": "Cuenta páginas de múltiples PDFs y exporta un informe.",
    "category": "pdf",
    "icon": "📄"
  },
  {
    "id": "enhanceScannedDocument",
    "toolId": "enhanceScannedDocument",
    "slug": "mejorar-documento-escaneado",
    "name": "Mejorar documento escaneado",
    "title": "Mejorar documento escaneado online gratis | Toolisto",
    "description": "Mejora la calidad de documentos escaneados o fotografiados ajustando brillo, contraste, nitidez y recortando bordes automáticamente.",
    "summary": "Corrige iluminación, contraste y nitidez de documentos escaneados directamente en tu navegador.",
    "category": "images",
    "icon": "⊞"
  },
  {
    "id": "cameraDocumentScanner",
    "toolId": "cameraDocumentScanner",
    "slug": "escanear-documento-camara",
    "name": "Escanear documento con cámara",
    "title": "Escanear documento con cámara online gratis | Toolisto",
    "description": "Captura documentos directamente con la cámara de tu dispositivo, corrige la perspectiva y mejora la calidad.",
    "summary": "Usa la cámara de tu dispositivo para capturar, corregir perspectiva y mejorar documentos.",
    "category": "images",
    "icon": "📷"
  },
  {
    "id": "pdfTablesToExcel",
    "toolId": "pdfTablesToExcel",
    "slug": "extraer-tablas-pdf-excel",
    "name": "Tablas PDF a Excel",
    "title": "Extraer tablas de PDF a Excel online gratis | Toolisto",
    "description": "Extrae tablas de documentos PDF y las exporta a formato Excel (XLSX) o CSV.",
    "summary": "Detecta y extrae tablas de PDFs directamente en tu navegador, exportando a Excel o CSV.",
    "category": "pdf",
    "icon": "📊"
  },
  {
    "id": "imageTableToExcel",
    "toolId": "imageTableToExcel",
    "slug": "extraer-tabla-imagen-excel",
    "name": "Tabla de imagen a Excel",
    "title": "Extraer tabla de imagen a Excel online gratis | Toolisto",
    "description": "Extrae tablas de una imagen usando OCR y las exporta a formato Excel o CSV.",
    "summary": "Reconoce tablas en imágenes mediante OCR y las exporta a Excel o CSV.",
    "category": "spreadsheets",
    "icon": "📊"
  },
  {
    "id": "convertAudio",
    "toolId": "convertAudio",
    "slug": "convertir-audio",
    "name": "Convertir audio",
    "title": "Convertir audio online gratis | Toolisto",
    "description": "Convierte archivos de audio entre formatos: MP3, WAV, OGG y AAC directamente en tu navegador.",
    "summary": "Transforma archivos de audio entre MP3, WAV, OGG y AAC sin subir a servidores.",
    "category": "audio",
    "icon": "🎵"
  },
  {
    "id": "trimAudio",
    "toolId": "trimAudio",
    "slug": "recortar-audio",
    "name": "Recortar audio",
    "title": "Recortar audio online gratis | Toolisto",
    "description": "Recorta archivos de audio seleccionando el rango de tiempo que necesitas.",
    "summary": "Elimina partes no deseadas de tus archivos de audio seleccionando inicio y fin.",
    "category": "audio",
    "icon": "✂"
  },
  {
    "id": "mergeAudio",
    "toolId": "mergeAudio",
    "slug": "unir-audios",
    "name": "Unir audios",
    "title": "Unir archivos de audio online gratis | Toolisto",
    "description": "Combina varios archivos de audio en uno solo, en el orden que elijas.",
    "summary": "Combina múltiples archivos de audio en un solo archivo directamente en tu navegador.",
    "category": "audio",
    "icon": "⊕"
  },
  {
    "id": "compressVideo",
    "toolId": "compressVideo",
    "slug": "comprimir-video",
    "name": "Comprimir video",
    "title": "Comprimir video online gratis | Toolisto",
    "description": "Reduce el tamaño de archivos de video cambiando calidad, resolución o formato.",
    "summary": "Reduce el peso de tus videos ajustando calidad y resolución directamente en el navegador.",
    "category": "video",
    "icon": "↘"
  },
  {
    "id": "trimVideo",
    "toolId": "trimVideo",
    "slug": "recortar-video",
    "name": "Recortar video",
    "title": "Recortar video online gratis | Toolisto",
    "description": "Recorta un video seleccionando el segmento de tiempo que necesitas.",
    "summary": "Elimina partes no deseadas de tus videos seleccionando inicio y fin.",
    "category": "video",
    "icon": "✂"
  },
  {
    "id": "mergeVideos",
    "toolId": "mergeVideos",
    "slug": "unir-videos",
    "name": "Unir videos",
    "title": "Unir videos online gratis | Toolisto",
    "description": "Combina varios videos en uno solo, en el orden que elijas.",
    "summary": "Combina múltiples videos en un solo archivo directamente en tu navegador.",
    "category": "video",
    "icon": "⊕"
  },
  {
    "id": "videoToGif",
    "toolId": "videoToGif",
    "slug": "video-a-gif",
    "name": "Video a GIF",
    "title": "Convertir video a GIF online gratis | Toolisto",
    "description": "Convierte un segmento de video en un GIF animado de alta calidad.",
    "summary": "Transforma un segmento de video en un GIF animado con control de calidad y tamaño.",
    "category": "video",
    "icon": "🎞"
  },
  {
    "id": "extractAudioFromVideo",
    "toolId": "extractAudioFromVideo",
    "slug": "extraer-audio-video",
    "name": "Extraer audio de video",
    "title": "Extraer audio de video online gratis | Toolisto",
    "description": "Extrae la pista de audio de un archivo de video y guárdalo como MP3, WAV o OGG.",
    "summary": "Separa el audio de un video y guárdalo como archivo de audio independiente.",
    "category": "audio",
    "icon": "🎵"
  },
  {
    "id": "removeAudioFromVideo",
    "toolId": "removeAudioFromVideo",
    "slug": "quitar-audio-video",
    "name": "Quitar audio de video",
    "title": "Quitar audio de video online gratis | Toolisto",
    "description": "Elimina la pista de audio de un video y descarga el video mudo.",
    "summary": "Elimina el sonido de un video para obtener un clip sin audio.",
    "category": "video",
    "icon": "🔇"
  },
  {
    "id": "inspectFileMetadata",
    "toolId": "inspectFileMetadata",
    "slug": "inspeccionar-metadatos-archivo",
    "name": "Inspeccionar metadatos de archivo",
    "title": "Inspeccionar metadatos de archivo online gratis | Toolisto",
    "description": "Analiza metadatos ocultos de archivos: EXIF, PDF, Office, ID3, hash SHA-256 y tipo real.",
    "summary": "Revela la información oculta de un archivo incluyendo metadatos EXIF, PDF, Office, audio y hash SHA-256.",
    "category": "files",
    "icon": "🔍"
  },
  {
    "id": "encryptDecryptFile",
    "toolId": "encryptDecryptFile",
    "slug": "cifrar-descifrar-archivo",
    "name": "Cifrar y descifrar archivos",
    "title": "Cifrar y descifrar archivos con contraseña online gratis | Toolisto",
    "description": "Protege tus archivos con cifrado AES-GCM-256. Descifra archivos .toolistoenc con tu contraseña.",
    "summary": "Cifrado AES-GCM-256 local: tu contraseña nunca sale del navegador.",
    "category": "files",
    "icon": "🔒"
  },
  {
    "id": "photoLocationExtractor",
    "toolId": "photoLocationExtractor",
    "slug": "extraer-ubicacion-foto",
    "name": "Extraer ubicación de foto",
    "title": "Extraer ubicación GPS de foto online gratis | Toolisto",
    "description": "Extrae las coordenadas GPS y datos de cámara de una imagen JPEG con datos EXIF.",
    "summary": "Lee los datos GPS y EXIF de tus fotos para saber dónde fueron tomadas.",
    "category": "images",
    "icon": "📍"
  },
  {
    "id": "simpleCalculator",
    "toolId": "simpleCalculator",
    "slug": "calculadora-simple",
    "name": "Calculadora simple",
    "title": "Calculadora simple online gratis | Toolisto",
    "description": "Calculadora básica con operaciones +, −, ×, ÷, porcentaje y memoria. Sin eval ni enviar datos.",
    "summary": "Operaciones básicas de forma segura directamente en tu navegador.",
    "category": "calculators",
    "icon": "🔢"
  },
  {
    "id": "scientificCalculator",
    "toolId": "scientificCalculator",
    "slug": "calculadora-cientifica",
    "name": "Calculadora científica",
    "title": "Calculadora científica online gratis | Toolisto",
    "description": "Calculadora con funciones trigonométricas, logarítmicas, potencias y radicales. 100% local.",
    "summary": "Funciones avanzadas de matemáticas sin enviar datos a ningún servidor.",
    "category": "calculators",
    "icon": "🧪"
  },
  {
    "id": "textToUnicodeBraille",
    "toolId": "textToUnicodeBraille",
    "slug": "texto-a-braille-unicode",
    "name": "Texto a Braille Unicode",
    "title": "Convertir texto a Braille Unicode online gratis | Toolisto",
    "description": "Convierte texto en español a caracteres Braille Unicode (U+2800–U+28FF) y viceversa.",
    "summary": "Codifica y decodifica texto en Braille español grado 1 sin salir del navegador.",
    "category": "text",
    "icon": "⠿"
  },
  {
    "id": "formatDocumentApa7",
    "toolId": "formatDocumentApa7",
    "slug": "formato-apa-7",
    "name": "Formato APA 7",
    "title": "Formato APA 7to edición online gratis | Toolisto",
    "description": "Formatea documentos estilo APA 7 con portada, resumen, cuerpo y referencias. Genera DOCX.",
    "summary": "Genera documentos con formato APA 7ed listos para imprimir o entregar.",
    "category": "documents",
    "icon": "📋"
  },
  {
    "id": "scannedPdfToSearchablePdf",
    "toolId": "scannedPdfToSearchablePdf",
    "slug": "pdf-escaneado-a-pdf-buscable",
    "name": "PDF escaneado a PDF buscable",
    "title": "Convertir PDF escaneado a PDF buscable online gratis | Toolisto",
    "description": "Convierte PDFs escaneados en PDFs con texto buscable y seleccionable usando OCR.",
    "summary": "Agrega una capa de texto invisible a PDFs escaneados para que el texto sea buscable y seleccionable.",
    "category": "pdf",
    "icon": "🔍"
  },
  {
    "id": "imageToSearchablePdf",
    "toolId": "imageToSearchablePdf",
    "slug": "imagen-a-pdf-buscable",
    "name": "Imagen a PDF buscable",
    "title": "Convertir imagen a PDF buscable con OCR online gratis | Toolisto",
    "description": "Convierte imágenes escaneadas o fotografiadas en PDFs con texto buscable usando OCR.",
    "summary": "Convierte fotos de documentos en PDFs con texto seleccionable y buscable.",
    "category": "pdf",
    "icon": "📄"
  },
  {
    "id": "extractTextFromScannedPdf",
    "toolId": "extractTextFromScannedPdf",
    "slug": "extraer-texto-pdf-escaneado",
    "name": "Extraer texto de PDF escaneado",
    "title": "Extraer texto de PDF escaneado con OCR online gratis | Toolisto",
    "description": "Extrae todo el texto de un PDF escaneado o imagen usando reconocimiento de caracteres (OCR).",
    "summary": "Obtén el texto editable de documentos escaneados o fotografiados.",
    "category": "pdf",
    "icon": "📝"
  },
  {
    "id": "detectOcrNeeded",
    "toolId": "detectOcrNeeded",
    "slug": "detectar-ocr-pdf",
    "name": "Detectar si PDF necesita OCR",
    "title": "Detectar si un PDF necesita OCR online gratis | Toolisto",
    "description": "Analiza un PDF y detecta automáticamente si tiene texto seleccionable o si necesita OCR.",
    "summary": "Verifica rápidamente si un PDF contiene texto real o si es solo una imagen escaneada.",
    "category": "pdf",
    "icon": "🔎"
  },
  {
    "id": "censorPdf",
    "toolId": "censorPdf",
    "slug": "censurar-pdf-permanente",
    "name": "Censurar PDF permanentemente",
    "title": "Censurar PDF permanentemente online gratis | Toolisto",
    "description": "Elimina permanentemente texto sensible de un PDF: zonas manuales, búsqueda de palabras, correos, teléfonos y documentos de identidad.",
    "summary": "Protege datos sensibles eliminando contenido real del PDF, no solo cubriéndolo.",
    "category": "pdf",
    "icon": "🛡"
  },
  {
    "id": "verifyPdfCensor",
    "toolId": "verifyPdfCensor",
    "slug": "verificar-censura-pdf",
    "name": "Verificar censura de PDF",
    "title": "Verificar censura de PDF online gratis | Toolisto",
    "description": "Comprueba si un PDF censurado aún contiene texto recuperable o información sensible.",
    "summary": "Valida que la censura de un PDF fue exitosa y no deja texto recuperable.",
    "category": "pdf",
    "icon": "✅"
  },
  {
    "id": "comparePdfs",
    "toolId": "comparePdfs",
    "slug": "comparar-dos-pdf",
    "name": "Comparar dos PDF",
    "title": "Comparar dos PDF documentos online gratis | Toolisto",
    "description": "Compara visual y textualmente dos PDFs, detectando páginas añadidas, eliminadas, modificadas y diferencias resaltadas.",
    "summary": "Encuentra todas las diferencias entre dos documentos PDF con reporte detallado.",
    "category": "pdf",
    "icon": "⚖"
  },
  {
    "id": "textStatistics",
    "toolId": "textStatistics",
    "slug": "estadisticas-texto",
    "name": "Estadísticas de texto",
    "title": "Estadísticas de texto online gratis | Toolisto",
    "description": "Analiza cualquier archivo de texto y obtén palabras, caracteres, frases, párrafos y tiempo de lectura.",
    "summary": "Obtén métricas completas de tu texto: palabras, caracteres, frases y tiempo de lectura.",
    "category": "text",
    "icon": "№"
  },
  {
    "id": "wordCount",
    "toolId": "wordCount",
    "slug": "contar-palabras",
    "name": "Contar palabras",
    "title": "Contar palabras online gratis | Toolisto",
    "description": "Cuenta palabras, caracteres y palabras únicas de cualquier archivo de texto al instante.",
    "summary": "Conoce el número exacto de palabras, caracteres y palabras únicas de tu texto.",
    "category": "text",
    "icon": "≡"
  },
  {
    "id": "textDiff",
    "toolId": "textDiff",
    "slug": "comparar-textos",
    "name": "Comparar textos",
    "title": "Comparar textos online gratis | Toolisto",
    "description": "Compara dos archivos de texto línea por línea y visualiza las diferencias entre ellos.",
    "summary": "Encuentra diferencias entre dos textos línea a línea con un informe claro.",
    "category": "text",
    "icon": "⇄"
  },
  {
    "id": "htmlToMarkdown",
    "toolId": "htmlToMarkdown",
    "slug": "html-a-markdown",
    "name": "HTML a Markdown",
    "title": "HTML a Markdown online gratis | Toolisto",
    "description": "Convierte archivos HTML a Markdown conservando encabezados, tablas, listas y enlaces.",
    "summary": "Transforma HTML a Markdown limpio y editable para documentación o blogs.",
    "category": "text",
    "icon": "↓"
  },
  {
    "id": "htmlToText",
    "toolId": "htmlToText",
    "slug": "html-a-texto",
    "name": "HTML a texto plano",
    "title": "HTML a texto plano online gratis | Toolisto",
    "description": "Extrae el texto visible de una página HTML eliminando etiquetas, scripts y estilos.",
    "summary": "Obtén solo el texto legible de cualquier archivo HTML.",
    "category": "text",
    "icon": "¶"
  },
  {
    "id": "cssMinifier",
    "toolId": "cssMinifier",
    "slug": "minificar-css",
    "name": "Minificar CSS",
    "title": "Minificar CSS online gratis | Toolisto",
    "description": "Reduce el tamaño de archivos CSS eliminando espacios, comentarios y caracteres innecesarios.",
    "summary": "Optimiza tu CSS eliminando espacios y comentarios para cargar páginas más rápido.",
    "category": "text",
    "icon": "{}"
  },
  {
    "id": "base64Encode",
    "toolId": "base64Encode",
    "slug": "codificar-base64",
    "name": "Codificar en Base64",
    "title": "Codificar en Base64 online gratis | Toolisto",
    "description": "Codifica el contenido de un archivo a formato Base64 para incrustarlo o transmitirlo.",
    "summary": "Convierte cualquier texto a Base64 con un clic.",
    "category": "text",
    "icon": "ⓑ"
  },
  {
    "id": "base64Decode",
    "toolId": "base64Decode",
    "slug": "decodificar-base64",
    "name": "Decodificar Base64",
    "title": "Decodificar Base64 online gratis | Toolisto",
    "description": "Convierte contenido Base64 de vuelta a texto legible o datos binarios originales.",
    "summary": "Decodifica texto Base64 a su contenido original.",
    "category": "text",
    "icon": "ⓓ"
  },
  {
    "id": "urlEncode",
    "toolId": "urlEncode",
    "slug": "codificar-url",
    "name": "Codificar URL",
    "title": "Codificar URL online gratis | Toolisto",
    "description": "Codifica el contenido de un archivo para utilizarlo de forma segura dentro de una URL.",
    "summary": "Convierte texto a formato URL-encoded compatible con navegadores y APIs.",
    "category": "text",
    "icon": "⇈"
  },
  {
    "id": "urlDecode",
    "toolId": "urlDecode",
    "slug": "decodificar-url",
    "name": "Decodificar URL",
    "title": "Decodificar URL online gratis | Toolisto",
    "description": "Convierte contenido codificado en URL de vuelta a texto legible.",
    "summary": "Decodifica secuencias %XX a caracteres normales.",
    "category": "text",
    "icon": "⇊"
  },
  {
    "id": "csvToMarkdown",
    "toolId": "csvToMarkdown",
    "slug": "csv-a-markdown",
    "name": "CSV a Markdown",
    "title": "CSV a Markdown online gratis | Toolisto",
    "description": "Convierte archivos CSV a tablas Markdown listas para GitHub, Notion o documentación.",
    "summary": "Transforma tus datos CSV en tablas Markdown alineadas.",
    "category": "spreadsheets",
    "icon": "▦"
  },
  {
    "id": "csvToHtml",
    "toolId": "csvToHtml",
    "slug": "csv-a-html",
    "name": "CSV a HTML",
    "title": "CSV a HTML online gratis | Toolisto",
    "description": "Convierte archivos CSV a una tabla HTML estilizada y lista para incrustar.",
    "summary": "Genera una tabla HTML con estilos básicos a partir de tu CSV.",
    "category": "spreadsheets",
    "icon": "☰"
  },
  {
    "id": "csvToYaml",
    "toolId": "csvToYaml",
    "slug": "csv-a-yaml",
    "name": "CSV a YAML",
    "title": "CSV a YAML online gratis | Toolisto",
    "description": "Convierte filas de un CSV en una lista de objetos YAML con sus columnas como claves.",
    "summary": "Transforma tus datos tabulares a YAML para configuración o pipelines.",
    "category": "spreadsheets",
    "icon": "⬛"
  },
  {
    "id": "excelToHtml",
    "toolId": "excelToHtml",
    "slug": "excel-a-html",
    "name": "Excel a HTML",
    "title": "Excel a HTML online gratis | Toolisto",
    "description": "Convierte hojas de Excel a tablas HTML estilizadas, conservando el contenido de cada celda.",
    "summary": "Convierte tus hojas de cálculo a HTML para web o informes.",
    "category": "spreadsheets",
    "icon": "⌘"
  },
  {
    "id": "excelToMarkdown",
    "toolId": "excelToMarkdown",
    "slug": "excel-a-markdown",
    "name": "Excel a Markdown",
    "title": "Excel a Markdown online gratis | Toolisto",
    "description": "Convierte hojas de Excel a tablas Markdown para documentación y repositorios.",
    "summary": "Exporta tus hojas de cálculo como tablas Markdown.",
    "category": "spreadsheets",
    "icon": "▤"
  },
  {
    "id": "xmlToExcel",
    "toolId": "xmlToExcel",
    "slug": "xml-a-excel",
    "name": "XML a Excel",
    "title": "XML a Excel online gratis | Toolisto",
    "description": "Extrae datos de archivos XML y los convierte en una tabla Excel editable.",
    "summary": "Convierte la información contenida en XML a una hoja de cálculo.",
    "category": "spreadsheets",
    "icon": "≣"
  },
  {
    "id": "csvStatistics",
    "toolId": "csvStatistics",
    "slug": "estadisticas-csv",
    "name": "Estadísticas CSV",
    "title": "Estadísticas CSV online gratis | Toolisto",
    "description": "Analiza un CSV y obtiene filas, columnas, valores vacíos y estadísticas numéricas por columna.",
    "summary": "Obtén métricas y análisis de tus archivos CSV al instante.",
    "category": "spreadsheets",
    "icon": "∑"
  },
  {
    "id": "csvFilter",
    "toolId": "csvFilter",
    "slug": "filtrar-csv",
    "name": "Filtrar CSV",
    "title": "Filtrar CSV online gratis | Toolisto",
    "description": "Filtra filas de un CSV por una condición de columna con operadores de comparación.",
    "summary": "Conserva solo las filas que cumplen la condición que elijas.",
    "category": "spreadsheets",
    "icon": "⌖"
  },
  {
    "id": "csvSort",
    "toolId": "csvSort",
    "slug": "ordenar-csv",
    "name": "Ordenar CSV",
    "title": "Ordenar CSV online gratis | Toolisto",
    "description": "Ordena las filas de un CSV por una columna en orden ascendente o descendente.",
    "summary": "Ordena tus datos CSV por cualquier columna.",
    "category": "spreadsheets",
    "icon": "⇅"
  },
  {
    "id": "csvToSql",
    "toolId": "csvToSql",
    "slug": "csv-a-sql",
    "name": "CSV a SQL",
    "title": "CSV a SQL online gratis | Toolisto",
    "description": "Genera sentencias CREATE TABLE e INSERT a partir de un CSV para importar a una base de datos.",
    "summary": "Convierte tu CSV en sentencias SQL listas para ejecutar.",
    "category": "spreadsheets",
    "icon": "🗄"
  },
  {
    "id": "jsonFormatter",
    "toolId": "jsonFormatter",
    "slug": "formatear-json",
    "name": "Formatear JSON",
    "title": "Formatear JSON online gratis | Toolisto",
    "description": "Formatea, valida y ordena archivos JSON para que sean legibles o compactos.",
    "summary": "Embellece o compacta tu JSON con indentación configurable.",
    "category": "spreadsheets",
    "icon": "⛁"
  },
  {
    "id": "excelToXml",
    "toolId": "excelToXml",
    "slug": "excel-a-xml",
    "name": "Excel a XML",
    "title": "Excel a XML online gratis | Toolisto",
    "description": "Convierte las hojas de un Excel a un documento XML estructurado con filas y celdas.",
    "summary": "Exporta tus hojas de cálculo a XML para intercambio de datos.",
    "category": "spreadsheets",
    "icon": "⛃"
  },
  {
    "id": "jsonValidator",
    "toolId": "jsonValidator",
    "slug": "validar-json",
    "name": "Validar JSON",
    "title": "Validar JSON online gratis | Toolisto",
    "description": "Valida la estructura de un archivo JSON y reporta errores de sintaxis con ubicación exacta.",
    "summary": "Comprueba si tu JSON es válido y dónde está el error si no lo es.",
    "category": "spreadsheets",
    "icon": "✓"
  }
];
